# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://zoechow24.github.io'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Zoe Chow
# Description of the Site
description: Portfolio
# URL of Image of the Site
site-image: assets/images/site-image.png
# Keywords of the Site
site-keywords: 
# URL for the Image of custom Favicon
favicon-url: assets/images/Z2.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://www.canva.com/design/DAGwogNH0jw/f_qXEg_YUavXMzDkO6uFdA/view?utm_content=DAGwogNH0jw&utm_campaign=designshare&utm_medium=link2&utm_source=uniquelinks&utlId=h8fb570b885

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: chow.zo@northeastern.edu
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username: zoe-chow-
github_username: zoechow24
youtube_channel_id:
reddit_username: 
behance_username:
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Zoe Chow
# URL for the Image of the Author
author-image: https://github.com/zoechow24.png
# 60 Words About the Author
author-about: I am currently a graduate student at Northeastern University pursuing my Master of Science in Bioinformatics and a research technician at Weill Cornell Medical School. I’m hoping to specialize in bioinformatics engineering, as I really enjoy designing and developing programs and also have a passion for medicine and genetics. I would like to one day bridge my interests and develop software tools for biological and/or medical advancements.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/zoechow24

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
















